# Generated by Django 4.1.1 on 2022-09-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_playerteam_player_alter_playerteam_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.ImageField(blank=True, upload_to="players"),
        ),
    ]
