# Generated by Django 4.1.1 on 2022-09-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_player_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="hltv",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="twitter",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
