# Generated by Django 4.1.1 on 2022-09-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_nationality_player_faceit_alter_player_hltv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="players.nationality",
            ),
        ),
    ]
