# Generated by Django 4.1.1 on 2022-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_player_nationality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="nationality",
        ),
        migrations.AddField(
            model_name="player",
            name="nationality",
            field=models.ManyToManyField(
                related_name="players", to="players.nationality"
            ),
        ),
    ]
