# Generated by Django 4.1.1 on 2022-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0007_remove_player_nationality_player_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
