# Generated by Django 4.1.1 on 2022-10-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0010_team_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="statistics",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
