FROM node:lts-alpine3.12 as build

WORKDIR /frontend
COPY package.json yarn.lock ./
RUN npm install
COPY . ./
RUN yarn build

FROM nginx:1.18.0-alpine

COPY /conf/default.conf /etc/nginx/conf.d/default.conf
COPY /conf/init.sh ./
COPY --from=build /frontend/build /usr/share/nginx/html
# CMD ["nginx", "-g", "daemon off;"]